####
## \file makefile.compilation
## \author Gardier Simon
## \date 26.10.2023
## \version 2.0
####

CC=gcc
LD=gcc
CFLAGS=--std=c99 --pedantic -Wall -Werror
LDFLAGS=
LIBLFSR=liblfsr.a
LIBPNM=libpnm.a
LIBUTILS=libutils.a
